name: Lint and Test CI
on: [push, pull_request]
jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Coverage
        run: npm run coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Trigger Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          gh workflow run release.yml --ref ${{ github.ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}